function MyFig1
%запускаем рабочее окно с элементами управления

%глобальные переменные, доступные из других функций
global hFig1 hAxes1 hAxes2;
global hEdxb hEdxe hEdN hEdyb hEdye hEdM;
global hEdx1 hEdy1 hEdI1 hEdf1;
global hEdxs1 hEdys1 hEdxs2 hEdys2;
global hBut1 hBut2;

%создаем окно 
hFig1 = figure(1);

%надпись над графическим объектом
hTxt1 = uicontrol(hFig1,'Style','text',...
    'String','Graphic Section',...
    'Position',[70 395 240 20],...
    'BackgroundColor',[0.7 0.7 0.9]);

%графический объект  - axes
hAxes1 = axes('Parent', hFig1, 'Color', [1 1 1],...
    'Units', 'points',...
    'Position', [90 50 90 90],...
    'FontSize', 6);

%графический объект  - axes
hAxes2 = axes('Parent', hFig1, 'Color', [1 1 1],...
    'Units', 'points',...
    'Position', [30 160 230 130],...
    'FontSize', 6);


%создаем элемент уравеления  - кнопку
hBut1 = uicontrol(hFig1,'Style','pushbutton',...
    'String','GO',...
    'Position',[50 10 110 30],...
    'Callback','MyGo');
%функция MyGo.m обрабатывает нажатие кнопки GO

%создаем элемент уравеления  - кнопку
hBut2 = uicontrol(hFig1,'Style','pushbutton',...
    'String','CLEAR',...
    'Position',[200 10 110 30],...
    'Callback','MyClear');
%функция MyClear.m обрабатывает нажатие кнопки CLEAR


%надпись над размерами области xy в которой рисуем поле
hTxt2 = uicontrol(hFig1,'Style','text',...
    'String','Parameters of area',...
    'Position',[400 395 120 15],...
    'BackgroundColor',[0.7 0.7 0.9]);

%размеры области xy в которой рисуем поле
%размеры по оси x
hTxtxb = uicontrol(hFig1,'Style','text',...
    'String','xb',...
    'Position',[360 370 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdxb = uicontrol(hFig1,'Style','edit',...
    'String','0',...
    'Position',[380 370 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtxe = uicontrol(hFig1,'Style','text',...
    'String','xe',...
    'Position',[430 370 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdxe = uicontrol(hFig1,'Style','edit',...
    'String','20',...
    'Position',[450 370 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

%число точек по оси x
hTxtN = uicontrol(hFig1,'Style','text',...
    'String','N',...
    'Position',[500 370 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdN = uicontrol(hFig1,'Style','edit',...
    'String','200',...
    'Position',[520 370 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

%размеры по оси y
hTxtyb = uicontrol(hFig1,'Style','text',...
    'String','yb',...
    'Position',[360 330 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdyb = uicontrol(hFig1,'Style','edit',...
    'String','0',...
    'Position',[380 330 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtye = uicontrol(hFig1,'Style','text',...
    'String','ye',...
    'Position',[430 330 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdye = uicontrol(hFig1,'Style','edit',...
    'String','20',...
    'Position',[450 330 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

%число точек по оси y
hTxtM = uicontrol(hFig1,'Style','text',...
    'String','M',...
    'Position',[500 330 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdM = uicontrol(hFig1,'Style','edit',...
    'String','100',...
    'Position',[520 330 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');


%надпись над параметрами антенны
hTxt3 = uicontrol(hFig1,'Style','text',...
    'String','Parameters of antenna 1',...
    'Position',[400 295 120 15],...
    'BackgroundColor',[0.7 0.7 0.9]);

hTxt4 = uicontrol(hFig1,'Style','text',...
    'String','Coordinates of antenna',...
    'Position',[400 275 120 15],...
    'BackgroundColor',[0.7 0.7 0.7]);

%координаты антенны
hTxtx1 = uicontrol(hFig1,'Style','text',...
    'String','x1',...
    'Position',[380 250 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdx1 = uicontrol(hFig1,'Style','edit',...
    'String','5',...
    'Position',[400 250 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxty1 = uicontrol(hFig1,'Style','text',...
    'String','y1',...
    'Position',[450 250 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdy1 = uicontrol(hFig1,'Style','edit',...
    'String','5',...
    'Position',[470 250 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxt5 = uicontrol(hFig1,'Style','text',...
    'String','Electric current in antenna',...
    'Position',[380 225 150 15],...
    'BackgroundColor',[0.7 0.7 0.7]);

%амплитуда и фаза тока
hTxtI1 = uicontrol(hFig1,'Style','text',...
    'String','I1',...
    'Position',[380 200 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdI1 = uicontrol(hFig1,'Style','edit',...
    'String','1',...
    'Position',[400 200 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtf1 = uicontrol(hFig1,'Style','text',...
    'String','f1',...
    'Position',[450 200 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdf1 = uicontrol(hFig1,'Style','edit',...
    'String','0',...
    'Position',[470 200 35 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');


%надпись над координатами сечения
hTxt6 = uicontrol(hFig1,'Style','text',...
    'String','Coordinates of Section',...
    'Position',[400 60 120 15],...
    'BackgroundColor',[0.7 0.7 0.9]);

%координаты сечения
hTxtxs1 = uicontrol(hFig1,'Style','text',...
    'String','xs1',...
    'Position',[400 35 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdxs1 = uicontrol(hFig1,'Style','edit',...
    'String','-5',...
    'Position',[420 35 30 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtys1 = uicontrol(hFig1,'Style','text',...
    'String','ys1',...
    'Position',[460 35 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdys1 = uicontrol(hFig1,'Style','edit',...
    'String','10',...
    'Position',[480 35 30 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtxs2 = uicontrol(hFig1,'Style','text',...
    'String','xs2',...
    'Position',[400 10 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdxs2 = uicontrol(hFig1,'Style','edit',...
    'String','15',...
    'Position',[420 10 30 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');

hTxtys2 = uicontrol(hFig1,'Style','text',...
    'String','ys2',...
    'Position',[460 10 20 20],...
    'BackgroundColor',[0.7 0.7 0.7]);
hEdys2 = uicontrol(hFig1,'Style','edit',...
    'String','0',...
    'Position',[480 10 30 20],...
    'BackgroundColor',[1 1 1],...
    'HorizontalAlignment','left');


%вертикальная черта
hTxt7 = uicontrol(hFig1,'Style','text',...
    'Position',[355 0 1 400],...
    'BackgroundColor',[0 0 0]);



